// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNYBsGCVQDePnFRly286CrdMTLax_oJkw',
    appId: '1:907517992568:web:0713a1b550065a3ce7578d',
    messagingSenderId: '907517992568',
    projectId: 'inventory-app-f1731',
    authDomain: 'inventory-app-f1731.firebaseapp.com',
    databaseURL: 'https://inventory-app-f1731-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-app-f1731.appspot.com',
    measurementId: 'G-8NK3H5LD9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw2LnOfoHjWJAg8EFPBOlclt18gl9uq_8',
    appId: '1:907517992568:android:6d8f95c89f7a0d4be7578d',
    messagingSenderId: '907517992568',
    projectId: 'inventory-app-f1731',
    databaseURL: 'https://inventory-app-f1731-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-app-f1731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ-cxsm6WdmS4Ns4o19rYe4YJNvbCXkQ0',
    appId: '1:907517992568:ios:7385b8081dbae598e7578d',
    messagingSenderId: '907517992568',
    projectId: 'inventory-app-f1731',
    databaseURL: 'https://inventory-app-f1731-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-app-f1731.appspot.com',
    iosBundleId: 'learn.danneir.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQ-cxsm6WdmS4Ns4o19rYe4YJNvbCXkQ0',
    appId: '1:907517992568:ios:f3cace8fa0997744e7578d',
    messagingSenderId: '907517992568',
    projectId: 'inventory-app-f1731',
    databaseURL: 'https://inventory-app-f1731-default-rtdb.firebaseio.com',
    storageBucket: 'inventory-app-f1731.appspot.com',
    iosBundleId: 'learn.danneir.push.RunnerTests',
  );
}
